---
title: "Evolutionary Genomics and Bioinformatics"
author: "Vista Sohrab"
date: "8/31/2020"
output: html_document
bibliography: data/references.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


This site provides links to labs from the Evolutionary Genomics and Bioinformatics course.

## Labs
#### R Basics

* 1: [Introduction to R and Reproducible Research](lab1_VistaSohrab.html)
* 2: [git, GitHub and Rstudio project](lab2_VistaSohrab.html)
* 3A: [Data Wrangling: Starting with the data](lab3A_VistaSohrab.html)
* 3B: [Data Wrangling: Manipulating and Analyzing Data with tidyverse](lab3B_VistaSohrab.html)
* 4: [Data Wrangling and Graphing COVID-19 Reporting Data - Part 1](lab4_VistaSohrab.html)
* 4a: [Data Visualization with ggplot2](lab4a_VistaSohrab.html)
* 5: [Data Wrangling and Graphing COVID-19 Reporting Data - Part 2](lab5_VistaSohrab.html)
* 5 Extra: [Interactive Graphs and Animations from the COVID-19 reporting data](lab5Extra_VistaSohrab.html)
* 6: [Data Maps and Interactive Graphs from the COVID-19 reporting data](lab6_VistaSohrab.html)
* 9: [Programming in R - Regular Expressions](lab9_VistaSohrab.html)
* 9 Extra: [Programming in R - Control Structures and Functions](lab9Extra_VistaSohrab.html)


#### Genomics
* 7: [RNA-Seq workflow: gene-level exploratory analysis and differential expression](lab7_VistaSohrab.html)
* 8: [Sequence Alignment, Phylogenetic Analysis and Tree Visualization](lab8_VistaSohrab.html)
* 10: [Population genomics based on high throughput sequencing (HTS)](lab10_VistaSohrab.html)

